### ISSUE TITLE
Migrations fail on a freshly cloned repo

### ISSUE THREAD

**Issue by deathowl** [openduty/openduty#54]
/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/environ/environ.py:630: UserWarning: /home/deathowl/work/odrework/openduty/config/settings/.env doesn't exist - if you're not configuring your environment separately, create one.
  "environment separately, create one." % env_file)
/home/deathowl/work/odrework/openduty/config/settings/__init__.py:102: UserWarning: SQLite URL contains host component 'openduty.db', it will be ignored
  'default': env.db('DATABASE_URL', default='sqlite://openduty.db')
Traceback (most recent call last):
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auth_group

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/urls/resolvers.py", line 571, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/urls/resolvers.py", line 564, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/deathowl/work/odrework/openduty/config/urls.py", line 43, in <module>
    path('events/', include('apps.events.urls')),
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/deathowl/work/odrework/openduty/apps/events/urls.py", line 2, in <module>
    from apps.events.views import CustomCreateEventView, CustomUpdateEventView, CustomDeleteEventView
  File "/home/deathowl/work/odrework/openduty/apps/events/views.py", line 9, in <module>
    from apps.events.forms import CustomEventForm
  File "/home/deathowl/work/odrework/openduty/apps/events/forms.py", line 11, in <module>
    class CustomEventForm(EventForm):
  File "/home/deathowl/work/odrework/openduty/apps/events/forms.py", line 26, in CustomEventForm
    ('Groups', [(x.name, x.name) for x in Group.objects.all()]),
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1097, in execute_sql
    cursor.execute(sql, params)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/deathowl/.virtualenvs/openduty/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auth_group

Please make migrations work @catalincoroeanu  so I can start code review properly.

**Comment by tkahnoski** [comment]
Just ran headfirst into this. It appears apps/events/forms.py has a class variable that is trying to execute a query. This doesn't work since the class variable is instantiated on any manage.py interaction.  Commenting out the calls that create 'on_call_choices' allows me to run migrations cleanly.
